### ISSUE TITLE
docker_* not working for me on osx with boot2docker

### ISSUE THREAD

**Issue by sckott** [wch/harbor#1]
Getting 

``` r
docker_cmd(host = localhost, cmd = "ps", args = "-a")

2014/10/23 16:47:00 Get http:///var/run/docker.sock/v1.13/containers/json?all=1: dial unix /var/run/docker.sock: no such file or directory
```

Does this have to do with the docker deamon not running?

**Comment by sckott** [comment]
@wch for this version check, i assume it should be `boot2docker` of version `x` or greater. What is the `x`? `v1.3`?

**Comment by sckott** [comment]
perhaps this for the version checker:

```r
boot2docker_ver <- function(){
  out <- docker_cmd(host = localhost, cmd = "-v", capture_text = TRUE)
  regmatches(out, regexpr("[0-9]+\\.[0-9]+\\.[0-9]+", out))
}

boot2docker_ver_check <- function(version = "1.3.0"){
  out <- boot2docker_ver()
  ver <- ver2num(out)
  checkver <- ver2num(version)
  ver > checkver
}

ver2num <- function(x) as.numeric(gsub("\\.", "", x))
```

On my box:

```r
<r> boot2docker_ver_check()

[1] TRUE
```

**Comment by wch** [comment]
I think you can use R's built in `as.package_version` instead of `ver2num` -- it's smart enough to handle separators correctly. For example:

```R
as.package_version('1.3.0') < as.package_version('1.10.2')
# TRUE
```

**Comment by wch** [comment]
Actually, won't that return the docker version, not the boot2docker version? Those are probably the same in most (maybe all) cases, but it's probably better to query boot2docker docker.

**Comment by sckott** [comment]
right, okay, `as.package_version()` is better 

you're right! overlooked that detail boot2docker ≠ docker
